//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBiblioteca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libro
    {
        public int idLibro { get; set; }

        [Display(Name = "Titulo")]
        public string titulo { get; set; }

        [Display(Name = "Autor(es)")]
        public string autor { get; set; }

        [Display(Name = "ISBN")]
        public string isbn { get; set; }

        [Display(Name = "Fecha de Publicacion")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha_publicacion { get; set; }

        [Display(Name = "Numero de Ejemplares")]
        public Nullable<int> numero_ejemplares { get; set; }

        [Display(Name = "Categoria")]
        public Nullable<int> idCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
