//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUBiblioteca
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Video
    {
        public int idVideo { get; set; }

        [Display(Name = "Titulo")]
        public string titulo { get; set; }

        [Display(Name = "Fecha de Publicacion")]
        [DisplayFormat(DataFormatString = "{0:dd/MMM/yyyy}")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> fecha_publicacion { get; set; }

        [Display(Name = "Formato")]
        public string formato { get; set; }

        [Display(Name = "Duración")]
        public Nullable<int> duracion { get; set; }


        [Display(Name = "Categoria")]
        public Nullable<int> idCategoria { get; set; }
    
        public virtual Categoria Categoria { get; set; }
    }
}
